"""Add week-based fields and edit history to Note model

Revision ID: 60006b2ab364
Revises: f78f3bbdbefd
Create Date: 2025-10-05 14:28:56.705834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60006b2ab364'
down_revision: Union[str, None] = 'f78f3bbdbefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('week_number', sa.Integer(), nullable=True, comment="Week number since user's birth (0-based)"))
    op.add_column('notes', sa.Column('note_date', sa.Date(), nullable=True, comment='Date when the note was written (for weekly organization)'))
    op.add_column('notes', sa.Column('edit_history', sa.JSON(), nullable=True, comment='JSON array of edit history entries'))
    op.create_index('ix_notes_owner_note_date', 'notes', ['owner_id', 'note_date'], unique=False)
    op.create_index('ix_notes_owner_week', 'notes', ['owner_id', 'week_number'], unique=False)
    op.create_index('ix_notes_week_date', 'notes', ['week_number', 'note_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_week_date', table_name='notes')
    op.drop_index('ix_notes_owner_week', table_name='notes')
    op.drop_index('ix_notes_owner_note_date', table_name='notes')
    op.drop_column('notes', 'edit_history')
    op.drop_column('notes', 'note_date')
    op.drop_column('notes', 'week_number')
    # ### end Alembic commands ###
