"""Remove category field from notes

Revision ID: cef4e358121e
Revises: 23281904674e
Create Date: 2025-10-14 09:37:23.978691

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cef4e358121e"
down_revision: Union[str, None] = "23281904674e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop category field and index if they exist
    try:
        op.drop_index("ix_notes_category", table_name="notes")
    except Exception:
        pass  # Index might not exist

    try:
        op.drop_column("notes", "category")
    except Exception:
        pass  # Column might not exist

    # Drop old indexes if they exist
    try:
        op.drop_index(
            "ix_users_new_email",
            table_name="users",
            sqlite_where=sa.text("email IS NOT NULL"),
        )
    except Exception:
        pass  # Index might not exist

    try:
        op.drop_index("ix_users_new_id", table_name="users")
    except Exception:
        pass  # Index might not exist

    try:
        op.drop_index("ix_users_new_username", table_name="users")
    except Exception:
        pass  # Index might not exist

    # Create new indexes if they don't exist
    try:
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    except Exception:
        pass  # Index might already exist

    try:
        op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    except Exception:
        pass  # Index might already exist

    try:
        op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    except Exception:
        pass  # Index might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop current indexes if they exist
    try:
        op.drop_index(op.f("ix_users_username"), table_name="users")
    except Exception:
        pass  # Index might not exist

    try:
        op.drop_index(op.f("ix_users_id"), table_name="users")
    except Exception:
        pass  # Index might not exist

    try:
        op.drop_index(op.f("ix_users_email"), table_name="users")
    except Exception:
        pass  # Index might not exist

    # Create old indexes if they don't exist
    try:
        op.create_index("ix_users_new_username", "users", ["username"], unique=False)
    except Exception:
        pass  # Index might already exist

    try:
        op.create_index("ix_users_new_id", "users", ["id"], unique=False)
    except Exception:
        pass  # Index might already exist

    try:
        op.create_index(
            "ix_users_new_email",
            "users",
            ["email"],
            unique=False,
            sqlite_where=sa.text("email IS NOT NULL"),
        )
    except Exception:
        pass  # Index might already exist

    # Add category column and index back
    try:
        op.add_column(
            "notes", sa.Column("category", sa.VARCHAR(length=100), nullable=True)
        )
    except Exception:
        pass  # Column might already exist

    try:
        op.create_index("ix_notes_category", "notes", ["category"], unique=False)
    except Exception:
        pass  # Index might already exist
    # ### end Alembic commands ###
