"""Add user profile fields and soft delete

Revision ID: f78f3bbdbefd
Revises: 97edff2bb60a
Create Date: 2025-10-05 13:34:06.287628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78f3bbdbefd'
down_revision: Union[str, None] = '97edff2bb60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True, comment="User's date of birth for life calculations"))
    op.add_column('users', sa.Column('lifespan', sa.Integer(), nullable=True, comment='Expected lifespan in years (default: 80)'))
    op.add_column('users', sa.Column('theme', sa.String(length=50), nullable=True, comment='UI theme preference (light/dark)'))
    op.add_column('users', sa.Column('font_size', sa.Integer(), nullable=True, comment='UI font size preference'))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag for user account'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when user was soft deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'font_size')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'lifespan')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
